version: '3.3'

services:

  pgadmin:
    image: dpage/pgadmin4:3.4
    container_name: pgadmin4
    ports:
      - 80:80
    env_file:
      - ./env/.pgadmin
    volumes:
      - pgadmin_vol:/var/lib/pgadmin

volumes:
  pgadmin_vol:
